Hardware spi
amperka/QuadDisplay2 pull request #1
Opened 2019-06-26 14:47 UTC by PSVM-J

@Igor89 проверь плз.

2019-06-26 14:52 UTC, Igor89 commented
Ок, сегодня гляну.

2019-06-26 14:54 UTC, nkrkv requested changes
С отступами — абзац. Прогоните через clang-format

2019-06-26 16:24 UTC, PSVM-J commented
Сорян.  Прогнал clang-format, конфиг с wiki/hq

2019-06-27 08:34 UTC, nkrkv requested changes

2019-06-27 08:34 UTC, nkrkv commented on QuadDisplay2.cpp
> +            array[i - 1] &= 0b11111110;
Это очень сложно понять. Что делает метод? Переносит точки из человекопонятного разряда на предыдущий хардварный, потому что так разведены регистры? Стоит написать doc-комментарий с примером.

Условие в `if` излишне сложное:

```cpp
if ((array[i] & 0x01 && i != 0) == 0) {

// Можно делать цикл с единицы, а не нуля. Тогда:
if ((array[i] & 0x01) == 0) {

// Убираем скобки
if (array[i] & 0x01 == 0) {

// Если используем двоичный литерал, давайте везде уж
if (array[i] & 0b000000001 == 0) {

```

2019-06-27 08:34 UTC, nkrkv commented on QuadDisplay2.cpp
> +        uint8_t* digitsArray = new uint8_t[4] { digit1, digit2, digit3, digit4 };
Неоправданное использование new-аллокации. Проще на стеке:

```cpp
uint8_t digitsArray[] = { digit1, digit2, digit3, digit4 };
```

Алсо, если мы перемешиваем точки на хардварном SPI, почему мы не делаем то же самое на софтварном??

2019-07-01 10:36 UTC, PSVM-J commented on QuadDisplay2.cpp
> +            array[i - 1] &= 0b11111110;
Метод с переносом точек приватный и предназначен не для пользователя.  Нужен для адекватного отображения точек при использовании хадварного SPI.  Т.к.  задефайненые символы сформированы с расчетом, что после передачи 
```C++
void QuadDisplay::writeData(uint8_t data, uint8_t n)
{
    shiftOut(_pinDI, _pinSCK, LSBFIRST, data);
}
```
 вызывается метод который пинает _pinSCK и продавливает в регистры 1 бит который всегда HIGH ))) 
```C++
void QuadDisplay::endWrite()
{
    digitalWrite(_pinDI, HIGH);
    digitalWrite(_pinSCK, HIGH);
    digitalWrite(_pinSCK, LOW);
    //
    digitalWrite(_pinCS, HIGH);
    digitalWrite(_pinDI, LOW);
    digitalWrite(_pinSCK, LOW);
}
```
Из за такого подхода, на индикаторе в принципе не возможно включить точку последнего индикатора. Ни таким способом. 
```C++
displayDigits(QD_DOT, QD_DOT, QD_DOT, QD_DOT);
```
Зажжёт точки на трёх индикаторах.
Толкнуть в SPI один бит я не могу физически, потому перекладываю точки в символах.

2019-07-01 14:13 UTC, PSVM-J commented on QuadDisplay2.cpp
> +        uint8_t* digitsArray = new uint8_t[4] { digit1, digit2, digit3, digit4 };
Согласен. Погорячился с new. Исправлено на стек.  Перемешивать придётся из за того, что текущая реализация библиотеки не позволит сразу выдать данные в SPI. Мешает метод endWrite(); который проталкивает в регистры 1 бит. SPI так делать не умеет. Потому пишу костыль. Так же чуть позже поправлю метод displaySegments().  
Или можно переписать библиотеку, учитывая что она должна быть полностью обратно совместима ?

2019-07-01 15:41 UTC, nkrkv commented on QuadDisplay2.cpp
> +        uint8_t* digitsArray = new uint8_t[4] { digit1, digit2, digit3, digit4 };
:ok_hand: 

Переписывать-переписывать редко имеет смысл. Лучше планомерно улучшать, момент за моментом. Вот в этой вилке soft/hard SPI есть корявость. С ней можно поработать. В этом PR или в новом не так важно. Важно, что не нужно для этого равнять всё бульдозером.

2019-07-01 15:43 UTC, nkrkv commented on QuadDisplay2.cpp
> +            array[i - 1] &= 0b11111110;
> Метод с переносом точек приватный и предназначен не для пользователя

В любом случае всю магию нужно комментировать. Хотя бы для тех, кто копается под капотом и по-честному хочет помочь: что-то улучшить или исправить баги.

Всё, что ты изложил выше — полезная информация, которой самое место в комментариях рядом с местом, где происходит магия.

2019-07-01 15:43 UTC, nkrkv approved these changes

2019-07-01 17:53 UTC, merged

2019-07-01 18:01 UTC, PSVM-J commented on QuadDisplay2.cpp
> +            array[i - 1] &= 0b11111110;
Смёржил. Ветку не удаляю потому как есть что ещё поправить, Комменты добавлю.